apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: docker.pkg.github.com/sam-atkins/voting-app/worker:0.3.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: DB_HOST
            value: postgres-store-cluster-ip-service
      imagePullSecrets:
        - name: dockerconfigjson-github-com
